version: "3.5"
services:
  base-server:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/sig-innove

  database:
    build:
      context: .docker/database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/database/data:/var/lib/postgresql/data
      - .docker/database/scripts:/etc/postgresql/scripts
    environment:
      POSTGRES_DB: "dbinnove"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    tty: true
